import numpy as np
import matplotlib.pyplot as plt
from scipy.special import zeta
import matplotlib as mpl
import scipy.integrate as integrate
from scipy import constants
from scipy import interpolate
from classy import Class
# modules for data I/O
import pickle
import os 
import time
import inspect
T0CMB = 2.7255 # in Kelvin
nu_factor = (4/11)**(1/3)  # T_nu0 (instantaneous decoupling) / T_CMB0
T0nu = T0CMB*0.71611 # with precise decoupling, in Kelvin
K_to_eV = constants.physical_constants['Boltzmann constant in eV/K'][0]
hbar = constants.physical_constants['reduced Planck constant in eV s'][0]
c = constants.speed_of_light
eV_to_cm = (hbar * c * 1e2)**(-1)  # eV to cm^-1

#
# Cosmology functions
#

# defining distributions
def f_FD(xi):
	return 1./(np.exp(xi)+1)
def f_BE(xi):
	return 1./(np.exp(xi)-1)
def f_RD(xi):
	return 2.19*pow(xi,-5./2.)*np.exp(-0.74*pow(xi,2.))
def f_LN(xi,sigma):
	return 1./(xi*sigma*np.sqrt(2*np.pi))*np.exp(-pow(np.log(xi),2)/(2*pow(sigma,2)))

# n-th moment of f(xi)
def Qn(f,n,sigma=1):
	if f in [f_FD,f_BE,f_RD]:
		return integrate.quad(lambda xi: xi**(2+n)*f(xi), 0, np.inf)[0]
	elif f == f_LN:
		return integrate.quad(lambda xi: xi**(2+n)*f(xi,sigma), 0, np.inf)[0]
	else: 
		log('Distrib not recognised, assuming FD.', level='ERROR')
		return integrate.quad(lambda xi: xi**(2+n)*f_FD(xi), 0, np.inf)[0]


def log(msg, level='INFO'):
	"""Small logging helper that auto-inserts source filename and caller function name.

	Format: [filename][function][LEVEL] message
	"""
	try:
		# Prefer the immediate caller frame; walk up if filename is non-informative.
		f = inspect.currentframe()
		caller = f.f_back
		# walk up until a sensible filename is found (not <string> or <stdin>) or we run out
		while caller is not None:
			fname = inspect.getframeinfo(caller).filename
			if fname and fname not in ('<string>', '<stdin>'):
				filename = os.path.basename(fname)
				func = caller.f_code.co_name
				break
			caller = caller.f_back
		else:
			# fallback
			filename = os.path.basename(__file__)
			func = '<module>'
	except Exception:
		filename = os.path.basename(__file__)
		func = '<module>'
	print(f'[{filename}][{func}][{level}]', msg)


def build_LN_Q_cache(sigma_array, output_dir='../data/distribution_data/LN_Q_cache/'):
	"""Ensure a pickle cache of Q0/Q1 for log-normal sigmas exists and return a dict sigma->(Q0,Q1).

	This cache speeds up repeated evaluations that depend only on the LN shape (not on cosmology).
	Missing sigmas will be computed and the cache updated on-disk.
	"""
	os.makedirs(output_dir, exist_ok=True)
	cache_file = os.path.join(output_dir, 'LN_Q_cache.pkl')
	if os.path.exists(cache_file):
		try:
			with open(cache_file, 'rb') as f:
				q_cache = pickle.load(f)
		except Exception:
			q_cache = {}
	else:
		q_cache = {}

	# compute missing entries
	for sigma in sigma_array:
		# use rounded key to avoid float precision discrepancies
		key = float(np.round(sigma, 10))
		if key in q_cache:
			continue
		Q0_sigma = Qn(f_LN, 0, sigma)
		Q1_sigma = Qn(f_LN, 1, sigma)
		q_cache[key] = (Q0_sigma, Q1_sigma)

	# save updated cache
	with open(cache_file, 'wb') as f:
		pickle.dump(q_cache, f)

	return q_cache

# characteristic momentum from 1st moment and Delta Neff (in units of the photon temp)
def T0chi(Q1,Delta_Neff,g):
	return pow(Delta_Neff/(g/2)/(Q1/(7*np.pi**4/120)),1/4)*nu_factor # in units of T_CMB0 for CLASS

# mass in eV
def m_chi(T0chi,z_NR,Q0,Q1):
	return T0chi*T0CMB*K_to_eV*(z_NR+1)*Q1/Q0

# LiMR physical matter density 
def omega_chi(Delta_Neff,z_NR):
	omega_gamma = 2.47298e-05 # in CLASS units
	return 7/8*nu_factor**4*Delta_Neff*(1+z_NR)*omega_gamma  

def asympt_scaling(a, Delta_Neff,z_NR):
	# returns the value of the joint power law defining the distribution independent asymptotic scalings of A(a) (see below chi_scaling function) at a
	# thus, it scales like a^-1 at early times and transitions to a^0 at late times
	a_NR = 1/(z_NR+1)

	return np.where(a < a_NR, a_NR/a, 1)

# Precomputed moments for canonical distributions
Q0_dict = {
	'FD':3/2*zeta(3),
	'BE':2*zeta(3),
	'RD':Qn(f_RD,0),
}

Q1_dict = {
	'FD':7*np.pi**4/120,
	'BE':6*np.pi**4/90,
	'RD':Qn(f_RD,1),
}

g_dict = {
	'FD':2,
	'BE':1,
	'RD':2,
	'LN':2,
}
	
def LiMR_parameters(Delta_Neff=0.3, z_NR=1e3, sigma_array=None, head_dir='../data/'):
	"""Return T0 and m dictionaries for the canonical distributions and (optionally) for a set of LN sigmas.

	If `sigma_array` is provided, this function will use a cached table of LN Q-moments (Q0,Q1)
	generated by `build_LN_Q_cache` to compute T0 and m for each sigma and include entries named
	`LN_{sigma:.3f}` in the returned dictionaries.
	"""

	T0_dict = {}
	m_dict = {}
	for case in ['FD', 'BE', 'RD']:
		# Compute T0 and m for canonical distributions
		T0_dict[case] = T0chi(Q1_dict[case], Delta_Neff, g_dict[case])
		m_dict[case] = m_chi(T0_dict[case], z_NR, Q0_dict[case], Q1_dict[case])

	# If sigma grid is requested, add entries for each sigma.
	# I need to modify this to allow single sigma or array of sigmas
	if type(sigma_array) is int or type(sigma_array) is float or type(sigma_array) is np.float64:
		sigma_array = np.asarray([sigma_array])
	if sigma_array is not None and len(sigma_array) > 0:
		# Ensure LN Q-cache exists for these sigmas
		output_dir = head_dir+'distribution_data/LN_Q_cache'
		q_cache = build_LN_Q_cache(sigma_array, output_dir=output_dir)
		for sigma in sigma_array:
			key = f'LN_{sigma:.3f}'
			sigma_key = float(np.round(sigma, 10))
			Q0_sigma, Q1_sigma = q_cache[sigma_key]
			T0_sigma = T0chi(Q1_sigma, Delta_Neff, 2)
			m_sigma = m_chi(T0_sigma, z_NR, Q0_sigma, Q1_sigma)
			T0_dict[key] = T0_sigma
			m_dict[key] = m_sigma

	return T0_dict, m_dict

# def_T0_dict, def_m_dict = LiMR_parameters(sigma_array=[0.04,1.5])

def chi_scaling(Delta_Neff=0.3,z_NR=1e3,case='FD',sigma=None):
	# returns the distribution dependent redshifting factor A(a) multiplying the present energy density to give a^3*rho(a) for a LiMR,
	# thus, it scales like a^-1 at early times and transitions to a^0 at late times
	# also gives the similar factors B(a) and C(a) = A(a) - B(a) for rho_rel(a) and rho_nr(a) = rho(a)-rho_rel(a) respectively, 
	# using that rho_rel(a) is prop to (three times) the pressure

	T0_dict, m_dict = LiMR_parameters(Delta_Neff,z_NR,sigma_array=sigma,head_dir='../data/')
	if case == 'LN':
		key = f'LN_{sigma:.3f}'
		T0 = T0_dict[key]
		m = m_dict[key]
	else:
		T0, m = T0_dict[case], m_dict[case]
	T0 = T0*T0CMB*K_to_eV
	f = eval(f'f_{case}')
	norm = m/T0*Qn(f,0,sigma=sigma)

	# smart choice for array of a values – needs to be dense around a_NR but can be sparse where linear elsewhere
	a_NR = 1/(z_NR+1)

	# a_array = np.concatenate([np.logspace(-6,np.log10(0.01*a_NR),10),np.logspace(np.log10(0.01*a_NR),np.log10(10*a_NR),100)[1:-1],np.logspace(np.log10(100*a_NR),0,10)])
	a_array = np.concatenate([np.logspace(-10,np.log10(0.999*a_NR),100),np.asarray([a_NR]),np.logspace(np.log10(1.001*a_NR),0,100)])

	A_array = []
	B_array = []
	for a in a_array:
		if case == 'LN':
			A_array.append(a**(-1)*integrate.quad(lambda xi: xi**2*np.sqrt(xi**2+(a*m/T0)**2)*f(xi,sigma), 0, np.inf)[0])
			B_array.append(3*a**(-1)*integrate.quad(lambda xi: xi**4/(3*np.sqrt(xi**2+(a*m/T0)**2))*f(xi,sigma), 0, np.inf)[0])
		else:
			# A uses the enrgy density integral, B uses the pressure integral
			A_array.append(a**(-1)*integrate.quad(lambda xi: xi**2*np.sqrt(xi**2+(a*m/T0)**2)*f(xi), 0, np.inf)[0])
			B_array.append(3*a**(-1)*integrate.quad(lambda xi: xi**4/(3*np.sqrt(xi**2+(a*m/T0)**2))*f(xi), 0, np.inf)[0])
	
	A_array = np.asarray(A_array)/norm
	B_array = np.asarray(B_array)/norm
	C_array = A_array - B_array
	
	A_func = interpolate.CubicSpline(a_array,A_array)
	B_func = interpolate.CubicSpline(a_array,B_array)
	C_func = interpolate.CubicSpline(a_array,C_array)

	return A_func, B_func, C_func

def ncdm_flags(case,sigma=None):
	ncdm_flags_dict = {
	'FD':'0,0,0',
	'BE':'1,0,0',
	'RD':'3,0,0',
	'LN':'2,0.5,0',#default sigma=0.5
	}
	if sigma != None:
		ncdm_flags_dict['LN'] = '2,'+str(sigma)+',0'
	return ncdm_flags_dict[case]

def ncdm_strategy(case,sigma=None,N_mnu=1):
	if case == 'RD' or (case == 'LN' and sigma != None and not 0.24 <= sigma <= 0.77):
		LiMR_strat = '3' #use adaptive quadrature for RD or LN if sigma is close to extrema as it speeds up sampling here over default
	else:
		LiMR_strat = '0' #default
	# vectorize output as string for N_mnu > 0 massive neutrinos
	if N_mnu > 0:
		return LiMR_strat + ',' + ','.join(['0' for x in range(N_mnu)]) # Potentially non-standard strategy for LiMR, default for massive nus
	else:
		return LiMR_strat

def ncdm_bins(case,N_mnu=1):
	# this function returns the minimum number of bins required to get suitable sampling accuracy for the RD or LN distribution in our custom scheme, vectorized for 1 LiMR + N_mnu massive nus
	# (Values are ignored for default sampler which uses adaptive scheme to minimize bins for each distribution)
	if case == 'RD':
		N_custom = 30
	else:
		N_custom = 20
	return ','.join([str(N_custom) for x in range(N_mnu+1)]) 

def ncdm_scaler(case,N_mnu=1):
	# this function returns the a-scaling factor for the custom quadrature scheme to ensure sufficient sampling of flat RD/LN distributions, vectorized for 1 LiMR + N_mnu massive nus
	# (Values are ignored for default sampler)
	if case == 'RD':
		a_scaler = 5.9 # this is simply value that returned expected values for DNeff and rho at late times in tests
	else:
		a_scaler = 1 # this will be overwritten with value from interpolation table for LN distribution
	return ','.join([str(a_scaler) for x in range(N_mnu+1)])

def ncdm_qmax(case,N_mnu=1):
	# this function returns the maximum q to sample for the custom quadrature scheme to ensure sufficient sampling of extended RD/LN distributions, vectorized for 1 LiMR + N_mnu massive nus
	# (Values are ignored for default sampler)
	if case == 'RD':
		qmax = 10
	else:
		qmax = 15 # this will be overwritten with value from interpolation table for LN distribution, and q_min != 0 chosen as well
	return ','.join([str(qmax) for x in range(N_mnu+1)])

def run_CLASS_and_save(case='LCDM', Delta_Neff=0.3, z_NR=1e3, sigma=None, T0_dict=None, m_dict=None, N_mnu = 1, M_mnu = 0.06, fixed1='h', fixed2='omega_m', head_dir='../data/',save=True):	
	"""Run CLASS for a given case and save outputs.

	This function writes a pickle with CLASS outputs. Files are written under `head_dir+'/fixed={fixed1},{fixed2}/N_mnu={str(N_mnu)}_Mmnu={str(M_mnu)}/'`.
	"""
	h = 0.67810                       # Dimensionless reduced Hubble parameter (H_0 / (100km/s/Mpc))
	theta_s100 = 1.051783             # Angular size of the sound horizon, exactly 100(ds_dec/da_dec)
	omega_m_LCDM = 0.1431354439            # Reduced total matter density (Omega*h^2) (Exactly, omega_m = omega_b + omega_cdm + omega_mnu with Mnu=0.06 eV)
	omega_cdm_LCDM = 0.1201075             # Reduced cold dark matter density in absence of LiMRs (Omega*h^2)
	omega_b = omega_m_LCDM - omega_cdm_LCDM



	if sigma == None:
		sigma = 0.5
	if T0_dict == None or m_dict == None:
		T0_dict, m_dict = LiMR_parameters(Delta_Neff,z_NR,[sigma],head_dir)
	
	nu_ur_array = [
		3.044,
		2.0308,
		1.0176,
		0.00441
	] # Massless neutrino contribution to Neff for N_mnu = 0,1,2,3 massive nus respectively

    # Initialize CLASS
	cosmo = Class()

    # Use default parameters
	cosmo.set({
		'output':'tCl,pCl,lCl,mPk',
		'P_k_max_1/Mpc':10,
		'l_max_scalars':2500,
		'lensing': 'yes',
		'write_background':'yes',            # Write background parameter table
		'background_verbose': 3,
		#'thermodynamics_verbose': 1,
		'perturbations_verbose': 1,
		'input_verbose': 1,
		#'transfer_verbose': 1,
		#'primordial_verbose': 1,
		#'harmonic_verbose': 1,
		#'fourier_verbose': 1,
		#'lensing_verbose': 1,
		'output_verbose': 1,
		'N_ur':nu_ur_array[N_mnu],
		'omega_b':omega_b,
	})

	if fixed2 == 'omega_m':
		cosmo.set({'omega_m':omega_m_LCDM})
		log(f'Fixed omega_m to {omega_m_LCDM}')
		# Fix physical matter density, meaning a_eq will decrease with increasing z_NR from that of the equivalent DNeff DR cosmology down to LCDM
		# Although this does not isolate effect of radiation driving (see, e.g., 2503.04671), it more closely matches MCMC output and keeps rho_tot fixed when H0 is also fixed
	elif fixed2 == 'a_eq':
		omega_gamma = 2.47298e-05
		def_a_eq = (1+7/8*pow(4/11,4/3)*3.044)*omega_gamma/(omega_cdm_LCDM+omega_b)
		log(f' Default a_eq = {def_a_eq}, corresponding to z_eq = {1/def_a_eq-1}')
		if case == 'LCDM':
			cosmo.set({'omega_cdm':omega_cdm_LCDM})
			log(f'Fixed omega_cdm to {omega_cdm_LCDM} for case LCDM')
		elif case == 'DR':	
			omega_c = omega_c = def_a_eq**(-1)*(1+7/8*pow(4/11,4/3)*(3.044+Delta_Neff))*omega_gamma - omega_b
			cosmo.set({'omega_cdm':omega_c})
			log(f'Adjusted omega_cdm to {omega_c} for case DR')
		else:
			omega_chi0 = omega_chi(Delta_Neff,z_NR)
			A_func, B_func, C_func = chi_scaling(Delta_Neff,z_NR,case,sigma)
			omega_c = def_a_eq**(-1)*(1+7/8*pow(4/11,4/3)*3.044)*omega_gamma + (B_func(def_a_eq)-C_func(def_a_eq))*omega_chi0-omega_b
			cosmo.set({'omega_cdm':omega_c})
			log(f'Adjusted omega_cdm to {omega_c} for case {case} of omega_chi = {omega_chi0}')

	fixed_str = 'fixed='+fixed1+','+fixed2
	output_dir = head_dir+fixed_str+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/'
	# if directory does not exist at this path create it now
	if not os.path.exists(output_dir):
		os.makedirs(output_dir)
		log(f'Created directory: {output_dir}')

	log(f'Computing CLASS with {case} parameters.')
	# Modify parameters if N_mnu > 0 
	
	if N_mnu>0:
		m_ncdm_str = ','.join([str(M_mnu/N_mnu) for x in range(N_mnu)]) # Baseline for LCDM and DR cosmologies, to be appended for LiMR cosmologies
		T_ncdm_str = ','.join(['0.71611' for x in range(N_mnu)])  # Standard neutrino temperature today in units of T_CMB0
		cosmo.set({
			'N_ncdm':N_mnu,
			'm_ncdm':m_ncdm_str,
			'T_ncdm':T_ncdm_str,
		})
		deg_ncdm_str = ','.join(['1' for x in range(N_mnu)]) # g = 2 for massive neutrinos
	
	# Now go case by case for non-LCDM cosmologies
	if case == 'DR':
		cosmo.set({
			'N_ur':nu_ur_array[N_mnu]+Delta_Neff,
		})
		root = output_dir+case+'_DNeff='+str(Delta_Neff)
	elif case in ['FD', 'BE', 'RD', 'LN']:
		root = output_dir+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)
		if case == 'LN':
			case_key = f'LN_{sigma:.3f}'
			root = root + '_sigma=' + str(sigma)
			log(f'Using LN sigma: {sigma}')
		else:
			case_key = case

		if N_mnu>0:
			m_ncdm_str = str(m_dict[case_key])+','+m_ncdm_str # Append LiMR mass to baseline neutrino masses if any
			T_ncdm_str = str(T0_dict[case_key])+','+T_ncdm_str # Append LiMR characteristic momentum to baseline neutrino temperatures if any	
			deg_ncdm_str = str(float(g_dict[case]/2))+','+deg_ncdm_str # Potentially non-standard deg_ncdm for LiMR, default for massive nus
		else:
			m_ncdm_str = str(m_dict[case_key])
			T_ncdm_str = str(T0_dict[case_key])
			deg_ncdm_str = str(float(g_dict[case]/2))
		
		cosmo.set({
			'N_ncdm':N_mnu+1,
			'm_ncdm':m_ncdm_str,
			'T_ncdm':T_ncdm_str,
			'deg_ncdm':deg_ncdm_str,
			'ncdm_psd_parameters':ncdm_flags(case,sigma),
			'ncdm_quadrature_strategy':ncdm_strategy(case,sigma,N_mnu),
			'ncdm_N_momentum_bins':ncdm_bins(case,N_mnu),
			'ncdm_a':ncdm_scaler(case,N_mnu),
			'ncdm_maximum_q':ncdm_qmax(case,N_mnu),
		})	
	else:
		root = output_dir+case
	if fixed1 == 'theta_s100':
		log('Fixed 100*theta_s requested, H0 will instead vary.')
		cosmo.set({'100*theta_s':theta_s100})
	
	# pip installed class allows writing parameters but not output files oddly, those have to be saved manually
	cosmo.set({
		'write parameters': 'yes',
		'root':root+'_',
	})

	time1 = time.time()
	cosmo.compute()
	time2 = time.time()
	log(f'CLASS computation took {time2-time1} seconds.')

	if fixed2 == 'a_eq':
		#check that a_eq was correctly fixed to def_a_eq
		a_eq = cosmo.get_current_derived_parameters(['a_eq'])['a_eq']
		log(f'Output a_eq = {a_eq}, corresponding to z_eq = {1/a_eq-1}')
		log(f'Percent different from def a_eq = {100*(a_eq-def_a_eq)/def_a_eq}. This small difference is due to massive neutrinos.')

	# save output to file
	filename = root + '_output.pkl'
	bg = cosmo.get_background()
	unlensed_cls = cosmo.raw_cl()
	lensed_cls = cosmo.lensed_cl()
	kvec = np.logspace(-4,1,2500)
	pk = [cosmo.pk(kk, 0.0) for kk in kvec]
	derived = cosmo.get_current_derived_parameters(['rs_rec', 'H0', 'z_reio', 'a_eq', '100*theta_s', 'z_rec'])
	output_data = {
		'background': bg,
		'unlensed_cls': unlensed_cls,
		'lensed_cls': lensed_cls,
		'kvec': kvec,
		'pk': pk,
		'derived': derived,
	}
	if save:
		with open(filename, 'wb') as f:
			pickle.dump(output_data, f)
		log(f'CLASS output saved to: {filename}')

	cosmo.struct_cleanup()
	cosmo.empty()

	return output_data

def test_CLASS(case='FD', Delta_Neff=0.3, z_NR=1e3, sigma=None, T0_dict=None, m_dict=None, N_mnu = 1, M_mnu = 0.06, fixed1='h', fixed2='omega_m', head_dir='../data/', save=False):
	log(f'Testing CLASS for case {case}.')
	log(f'If LiMR, Delta_Neff = {Delta_Neff}, z_NR = {z_NR}')
	log(f'Thus, if LiMR, omega_chi shoud be {omega_chi(Delta_Neff,z_NR)}')
	output_data = run_CLASS_and_save(case, Delta_Neff, z_NR, sigma, T0_dict, m_dict, N_mnu, M_mnu, fixed1, fixed2, head_dir, save)

def fill_cosmos(cases=['LCDM', 'DR', 'FD'], Delta_Neff=0.3, z_NR=1e3, sigma_array=[0.04,1.5], T0_dict=None, m_dict=None, N_mnu = 1, M_mnu = 0.06, fixed1='h', fixed2='omega_m', head_dir='../data/'):
	""" Pickle output from CLASS for a set of cosmological cases.
	Then create global variables for each case with the output data.
	"""
	fixed_str = 'fixed='+fixed1+','+fixed2
	output_dir = head_dir+fixed_str+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/'
	for case in cases:
		root = output_dir+case
		if case != 'LN':
			if case == 'DR':
				root = output_dir+case+'_DNeff='+str(Delta_Neff)
			elif case in ['FD', 'BE', 'RD']:
				root = output_dir+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)
			filename = root + '_output.pkl'
			if os.path.exists(filename):
				with open(filename, 'rb') as f:
					output_data = pickle.load(f)
					log(f'Loaded CLASS output for {case} from: {filename}')
			else:
				output_data = run_CLASS_and_save(case, Delta_Neff, z_NR, T0_dict=T0_dict, m_dict=m_dict, N_mnu=N_mnu, M_mnu=M_mnu, fixed1=fixed1, fixed2=fixed2, head_dir=head_dir)
				log(f'Saved CLASS output for {case} to: {filename}')
			globals()[f'cosmo_{root}'] = output_data
		else:
			for sigma in sigma_array:
				root = output_dir+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)+'_sigma='+str(sigma)
				filename = root + '_output.pkl'
				if os.path.exists(filename):
					with open(filename, 'rb') as f:
						output_data = pickle.load(f)
						log(f'Loaded CLASS output for {case} from: {filename}')
				else:
					output_data = run_CLASS_and_save(case, Delta_Neff, z_NR, sigma=sigma, T0_dict=T0_dict, m_dict=m_dict, N_mnu=N_mnu, M_mnu=M_mnu, fixed1=fixed1, fixed2=fixed2, head_dir=head_dir)
					log(f'Saved CLASS output for {case} to: {filename}')
				globals()[f'cosmo_{root}'] = output_data

#
# Plotting functions
#
def plot_distributions(ax,Delta_Neff=0.3,z_NR=1e3,sigma_array=[0.04,1.5],ins=False):
	# plot curves, that when integrated over log \xi would give the non-relativistic energy density for LiMRs of the given Delta_Neff and z_NR
	# choose LN sigma grid for plotting continuous band

	# request LiMR parameters including per-sigma entries (this uses the LN Q-cache)
	T0_dict, m_dict = LiMR_parameters(Delta_Neff, z_NR, sigma_array=sigma_array)
	xi_array = np.geomspace(1e-4, 1e5, 40000)
	ymax = 0.
	
	# Now plot LN sigma band 
	c0 = mpl.colors.to_rgb(cosmo_color('LNsharp'))
	c1 = mpl.colors.to_rgb(cosmo_color('LNwide'))
	for i, sigma in enumerate(sigma_array[::-1]):
		key = f'LN_{sigma:.3f}'

		m_sigma = m_dict[key]
		T0_sigma = T0_dict[key]
		curve = m_sigma*(T0_sigma*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict['LN'] / (2 * np.pi**2) * f_LN(xi_array,sigma) * xi_array**3
		t = float((len(sigma_array) - 1) - i) / (len(sigma_array) - 1)
		color = (c0[0] * (1 - t) + c1[0] * t,
				 c0[1] * (1 - t) + c1[1] * t,
				 c0[2] * (1 - t) + c1[2] * t)
		if ins:
			ax.plot(xi_array, curve, c=color, alpha=0.1*(.1+sigma)/1.6, lw=1.5) # necessary since otherwise sharp curves bunch up in linear yspace
		else:
			ax.plot(xi_array, curve, c=color, alpha=0.1, lw=1.5)
		# emphasize endpoints
		if i == 0 or i == len(sigma_array)-1:
			ax.plot(xi_array, curve, c=color, lw=1.5)

	# Now plot canonical distributions
	for case in ['FD', 'BE', 'RD']:
		d_rhoNR_dlogq = lambda xi, case=case: m_dict[case]*(T0_dict[case]*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict[case] / (2 * np.pi**2) * eval(f'f_{case}(xi)') * xi**3
		ax.plot(
			xi_array,
			d_rhoNR_dlogq(xi_array),
			c=cosmo_color(case),
			lw=1.5,
			label=case)
		peak_value = np.max(d_rhoNR_dlogq(xi_array))
		if peak_value > ymax:
			ymax = peak_value
	

	ymax = ymax / 0.5
	ymax_rounded = round(ymax, -int(np.floor(np.log10(ymax))))	

	
	return ymax_rounded

def plot_cosmo_densities(Delta_Neffs=[0.3,0.094,0.02], z_NRs =[1e3,1e4,1e5], N_mnu = 1, M_mnu = 0.06, head_dir='../data/'):
	"""
	This function plots the bg energy density evolution for LCDM (with N_mnu massive neutrinos) and for possibly multiple FD LiMR cosmologies.
	It assumes H0 is fixed to 67.81 km/s/Mpc
	"""
	cs = IBM_cscheme()
	
	# fill out arrays for background values for plotting, using fill_cosmos
	for i, Delta_Neff in enumerate(Delta_Neffs):
		fill_cosmos(cases=['LCDM','DR','FD'], Delta_Neff=Delta_Neff, z_NR=z_NRs[i], N_mnu=N_mnu, M_mnu=M_mnu, head_dir=head_dir)

	log(f'Plotting background density evolution for {N_mnu} massive neutrinos of {M_mnu} total eV.')
	root = head_dir+'fixed=h,omega_m/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/LCDM'
	z_array = globals()[f'cosmo_{root}']['background']['z']
	a_array = 1/(1+z_array)
	rho_g = globals()[f'cosmo_{root}']['background']['(.)rho_g']
	rho_cdm_LCDM = globals()[f'cosmo_{root}']['background']['(.)rho_cdm']
	rho_ur_LCDM = globals()[f'cosmo_{root}']['background']['(.)rho_ur'] # first include ur contribution to rho_nu
	rho_mnu_tot = 0
	p_mnu_tot = 0
	for ncdm_index in range(N_mnu):
		# then add massive neutrino contribution (corresponding to keys (.)rho_ncdm[0] - (.)rho_ncdm[N_mnu] for LCDM)
		rho_mnu_tot += globals()[f'cosmo_{root}']['background'][f'(.)rho_ncdm[{ncdm_index}]']
		p_mnu_tot += globals()[f'cosmo_{root}']['background'][f'(.)p_ncdm[{ncdm_index}]']
	
	rho_b = globals()[f'cosmo_{root}']['background']['(.)rho_b']
	rho_nu_tot = rho_ur_LCDM + rho_mnu_tot
	rho_m_LCDM = rho_cdm_LCDM + rho_b + rho_mnu_tot - 3*p_mnu_tot # need to subtract off relativistic contribution from massive nu's and ur species

	rho_lambda = globals()[f'cosmo_{root}']['background']['(.)rho_lambda']
	rho_crit = globals()[f'cosmo_{root}']['background']['(.)rho_crit']

	for rhos in [rho_g, rho_m_LCDM, rho_nu_tot, rho_lambda]:
		Omega_i = rhos/rho_crit
		plt.loglog(
			a_array,
			Omega_i,
			c='k',
			lw=1.0,
			zorder=1,
			# label=rhos
			)
		
	plt.text(1.8e-6, 6.5e-1, r'$\mathrm{Photons}$', rotation=0, fontsize=12)
	plt.text(1.5e-6, 2.8e-1, r'$\mathrm{Neutrinos}$', rotation=0, fontsize=12)
	if N_mnu > 0:
		plt.text(1.5e-6, 2e-1, r'$(\Sigma m_\nu = '+str(M_mnu)+'\,\mathrm{eV})$', rotation=0, fontsize=10)
	plt.text(1.3e-2, 1.1, r'$\mathrm{Total\,\,Matter}$', rotation=0, fontsize=12)
	plt.text(2.8e-2, 1.5e-4, r'$\mathrm{Dark\,\,Energy}$', rotation=68, fontsize=12)

	a_eq = globals()[f'cosmo_{root}']['derived']['a_eq']
	z_rec = globals()[f'cosmo_{root}']['derived']['z_rec']
	a_rec = 1/(1+z_rec)

	# plt.axvline(a_eq, c='gray', ls='-', lw=1.0, alpha=0.7, zorder=0)
	# plt.axvline(a_rec, c='gray', ls='-', lw=1.0, alpha=0.7, zorder=0)

	# plt.text(0.65*a_eq, 1.6e-3, r'$z_{\mathrm{eq}}$', rotation=90, fontsize=14, color='gray')
	# plt.text(0.65*a_rec, 1.6e-3, r'$z_{\mathrm{rec}}$', rotation=90, fontsize=14, color='gray')

	log('Now for LiMR cosmologies...')

	for i, Delta_Neff in enumerate(Delta_Neffs):
		DR_root = head_dir+'fixed=h,omega_m/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/DR_DNeff='+str(Delta_Neff)
		LiMR_root = head_dir+'fixed=h,omega_m/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/FD_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NRs[i])
		rho_equiv_DR = globals()[f'cosmo_{DR_root}']['background']['(.)rho_ur']-rho_ur_LCDM
		rho_LiMR = globals()[f'cosmo_{LiMR_root}']['background']['(.)rho_ncdm[0]']
		rho_cdm_LiMR = globals()[f'cosmo_{LiMR_root}']['background']['(.)rho_cdm']
		p_LiMR = globals()[f'cosmo_{LiMR_root}']['background']['(.)p_ncdm[0]']
		rho_m_LiMR = rho_m_LCDM - rho_cdm_LCDM + rho_cdm_LiMR + rho_LiMR - 3*p_LiMR
		rho_dict = {
			'LiMR':rho_LiMR,
			'DR':rho_equiv_DR,
			'm_tot':rho_m_LiMR,
		}

		# for j, rhos in enumerate([rho_LiMR,rho_equiv_DR]):
		for species in ['LiMR','DR']:
			rhos = rho_dict[species]
			Omega_i = rhos/rho_crit
			if species == 'LiMR':
				plt.loglog(
					a_array,
					Omega_i,
					c = cs[2*i%5],
					lw=2.0,
					ls='-',
					# zorder=0,
					label=gen_label(Delta_Neffs[i],z_NRs[i])
				)
			elif species == 'DR':
				plt.loglog(
					a_array,
					Omega_i,
					c = cs[2*i%5],
					lw=1.5,
					ls='--',
					# zorder=0,
				)
			elif species == 'm_tot':
				plt.loglog(
					a_array,
					Omega_i,
					c = cs[2*i%5],
					lw=2.0,
					ls='-',
					# zorder=0,
				)
		a_NR = 1/(1+z_NRs[i])
		# plt.axvline(a_NR, c=cs[2*i%5], ls='--', lw=1.0, alpha=0.7, zorder=0)
	plt.legend(fontsize=12,loc='lower left', frameon=False)

def plot_vs_LCDM_Cl(Delta_Neffs=[0.3,0.094,0.02], z_NRs =[1e3,1e4,1e5], N_mnu = 1, M_mnu = 0.06, fixed1='h', fixed2='omega_m', lensed=True, spectra='tt', head_dir='../data/'):
	"""
	This function plots the Cl residuals w.r.t LCDM (with N_mnu massive neutrinos) for DR and FD LiMR cosmologies.
	"""
	cs = IBM_cscheme()
	fixed_str = 'fixed='+fixed1+','+fixed2
	# fill out arrays for cl values for plotting, using fill_cosmos
	fill_cosmos(cases=['LCDM'], N_mnu=N_mnu, M_mnu=M_mnu, fixed1=fixed1, fixed2=fixed2, head_dir=head_dir)
	root = head_dir+fixed_str+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/LCDM'
	ell = globals()[f'cosmo_{root}']['lensed_cls']['ell'][2:]
	lensed_clTT_LCDM = globals()[f'cosmo_{root}']['lensed_cls'][spectra][2:]
	unlensed_clTT_LCDM = globals()[f'cosmo_{root}']['unlensed_cls'][spectra][2:2501]

	for i, Delta_Neff in enumerate(Delta_Neffs):
		fill_cosmos(cases=['DR','FD'], Delta_Neff=Delta_Neff, z_NR=z_NRs[i], N_mnu=N_mnu, M_mnu=M_mnu, fixed1=fixed1, fixed2=fixed2, head_dir=head_dir)
		for case in ['DR','FD']:
			if case == 'DR':
				root = head_dir+fixed_str+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/DR_DNeff='+str(Delta_Neff)
				label = r'$\Delta N_{\mathrm{eff}}='+str(Delta_Neff)+'$'
				label = ''
			elif case == 'FD':
				root = head_dir+fixed_str+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/FD_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NRs[i])
				label = gen_label(Delta_Neffs[i],z_NRs[i])
			lensed_clTT = globals()[f'cosmo_{root}']['lensed_cls'][spectra][2:]
			unlensed_clTT = globals()[f'cosmo_{root}']['unlensed_cls'][spectra][2:2501]
			if lensed:
				plt.plot(
					ell,
					(lensed_clTT_LCDM-lensed_clTT)/lensed_clTT_LCDM,
					c=cs[2*i%5],
					lw=1.5 if case == 'FD' else 1.0,
					ls='-' if case == 'FD' else '--',
					label=label,
					# zorder=0,
					# label=gen_label(Delta_Neffs[i],z_NRs[i])
				)
			else:
				plt.plot(
					ell,
					(unlensed_clTT_LCDM-unlensed_clTT)/unlensed_clTT_LCDM,
					c=cs[2*i%5],
					lw=1.5 if case == 'FD' else 1.0,
					ls='-' if case == 'FD' else '--',
					label=label,		
					# zorder=0,
				)
	plt.legend(fontsize=12,loc='lower left', frameon=False)
			



def plot_evolution(Delta_Neff=0.3,z_NR=1e3,sigma_array=[0.04,1.5],head_dir='../data/'):
	"""
	This plots the evolution of each LiMR species through the transition, normalized the the asymptotic scalings
	"""
	cases = ['FD','BE','RD','LN']
	# fill out arrays for background values for plotting, using fill_cosmos
	fill_cosmos(cases=cases, Delta_Neff=Delta_Neff, z_NR=z_NR, sigma_array=sigma_array,head_dir=head_dir)

	for case in cases:
		if case != 'LN':
			root = head_dir+'fixed=h,omega_m/N_mnu=1_Mmnu=0.06/'+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)
			# get the relevant background values
			rho_LiMR = globals()[f'cosmo_{root}']['background']['(.)rho_ncdm[0]']

			if case == 'FD':
				z_array = globals()[f'cosmo_{root}']['background']['z']
				a_array = 1/(1+z_array)
				rho_LiMR_asympt =(1+z_array)**3*asympt_scaling(1/(1+z_array),Delta_Neff,z_NR)*rho_LiMR[-1]
				# rho_LiMR_asympt = rho_LiMR in case I want to see result wrt FD

			plt.semilogx(z_array,rho_LiMR/rho_LiMR_asympt,label=f'{case} LiMR',ls='-', lw=1.5, c=cosmo_color(case))	
		else:
			c0 = mpl.colors.to_rgb(cosmo_color('LNsharp'))
			c1 = mpl.colors.to_rgb(cosmo_color('LNwide'))
			for i, sigma in enumerate(sigma_array):
				root = head_dir+'fixed=h,omega_m/N_mnu=1_Mmnu=0.06/'+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)+'_sigma='+str(sigma)
				rho_LiMR = globals()[f'cosmo_{root}']['background']['(.)rho_ncdm[0]']
				# plot same ratios as above, but with color coding for sigma as in plot_distributions

				t = float(i) / (len(sigma_array) - 1)
				color = (c0[0] * (1 - t) + c1[0] * t,
						 c0[1] * (1 - t) + c1[1] * t,
						 c0[2] * (1 - t) + c1[2] * t)
				plt.semilogx(z_array,rho_LiMR/rho_LiMR_asympt,ls='-',c=color, alpha=0.1, lw=1.5,zorder=0)
				if i == 0 or i == len(sigma_array)-1:
					plt.semilogx(z_array,rho_LiMR/rho_LiMR_asympt,ls='-',c=color, lw=1.5)	
				

	# now add vertical line at z_NR
	plt.axvline(z_NR, c='gray', ls='-', lw=1.0, alpha=0.7)	

def plot_distrib_cls(Delta_Neff=0.3,z_NR=1e3,sigma_array=[0.04,1.5],denom='FD',lensed=True,head_dir='../data/',fixed1='h',fixed2='omega_m',N_mnu=1,M_mnu=0.06):
	""" This function plots the residuals for the LiMR cosmologies w.r.t. either FD or DR
	"""
	# denom = 'BE'
	cases=['DR',denom,'FD','BE','RD','LN'] # add denom in case I want to plot in different order
	ell = {}
	lensed_clTT = {}
	unlensed_clTT = {}
	
	fill_cosmos(cases=cases, Delta_Neff=Delta_Neff,z_NR=z_NR,sigma_array=sigma_array, N_mnu=N_mnu, M_mnu=M_mnu, fixed1=fixed1, fixed2=fixed2, head_dir=head_dir)
	for case in cases:
		if case == 'DR':
			root = head_dir+'fixed='+fixed1+','+fixed2+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/DR_DNeff='+str(Delta_Neff)
			ell[case] = globals()[f'cosmo_{root}']['lensed_cls']['ell'][2:]
			lensed_clTT[case] = globals()[f'cosmo_{root}']['lensed_cls']['tt'][2:]
			unlensed_clTT[case] = globals()[f'cosmo_{root}']['unlensed_cls']['tt'][2:2501]

		elif case != 'LN':
			root = head_dir+'fixed='+fixed1+','+fixed2+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/'+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)
			ell[case] = globals()[f'cosmo_{root}']['lensed_cls']['ell'][2:]
			lensed_clTT[case] = globals()[f'cosmo_{root}']['lensed_cls']['tt'][2:]
			unlensed_clTT[case] = globals()[f'cosmo_{root}']['unlensed_cls']['tt'][2:2501]

			if lensed:
				plt.plot(
					ell[case],
					(lensed_clTT[case]-lensed_clTT[denom])/lensed_clTT[denom],
					c=cosmo_color(case),
					lw = 1.5
				)
			else:
				plt.plot(
					ell[case],
					(unlensed_clTT[case]-unlensed_clTT[denom])/unlensed_clTT[denom],
					c=cosmo_color(case),
					lw = 1.5
				)
		else:
			c0 = mpl.colors.to_rgb(cosmo_color('LNsharp'))
			c1 = mpl.colors.to_rgb(cosmo_color('LNwide'))
			for i, sigma in enumerate(sigma_array):
				root = head_dir+'fixed='+fixed1+','+fixed2+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/'+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)+'_sigma='+str(sigma)
				ell[case] = globals()[f'cosmo_{root}']['lensed_cls']['ell'][2:]
				lensed_clTT[case] = globals()[f'cosmo_{root}']['lensed_cls']['tt'][2:]
				unlensed_clTT[case] = globals()[f'cosmo_{root}']['unlensed_cls']['tt'][2:2501]

				t = float(i) / (len(sigma_array) - 1)
				color = (c0[0] * (1 - t) + c1[0] * t,
						 c0[1] * (1 - t) + c1[1] * t,
						 c0[2] * (1 - t) + c1[2] * t)
				if lensed:
					plt.plot(
						ell[case],
						(lensed_clTT[case]-lensed_clTT[denom])/lensed_clTT[denom],
						c=color,
						lw = 1.5,
						alpha= 1 if i == 0 or i == len(sigma_array)-1 else 0.1,
						zorder=0
					)
				else:
					plt.plot(
						ell[case],
						(unlensed_clTT[case]-unlensed_clTT[denom])/unlensed_clTT[denom],
						c=color,
						lw = 1.5,
						alpha= 1 if i == 0 or i == len(sigma_array)-1 else 0.1,
						zorder=0
					)



def plot_scaling(Delta_Neff=0.3,z_NR=1e3,case='FD',sigma=None):
	A_func, B_func, C_func = chi_scaling(Delta_Neff,z_NR,case,sigma)
	a_array = np.logspace(-6,0,1000)

	plt.loglog(a_array,A_func(a_array),label=r'$A(a)\propto \rho_\chi(a)$')
	plt.loglog(a_array,B_func(a_array),label=r'$B(a)\propto \rho^\mathrm{rel}_\chi(a)$')
	plt.loglog(a_array,C_func(a_array),label=r'$C(a)\propto \rho^\mathrm{nr}_\chi(a)$')
	plt.xlabel(r'$a$')
	plt.ylabel(r'$R(a)$')

	a_NR = 1/(z_NR+1)
	set_xy_lims(xmin=0.1*a_NR, xmax=10*a_NR, ymin=0.1, ymax=A_func(0.1*a_NR))
	# add vertical line at a_NR
	plt.axvline(a_NR, c='gray', ls='--', lw=1.0, alpha=0.5)
	plt.legend()

# Plotting visual settings
def IBM_cscheme():
	return [
		'#dc267f',
		'#785ef0',
		'#648fff',
		'#ffb000',
		'#fe6100',
	]

def gen_label(Delta_Neff,z_NR):
	log10z_NR = round(np.log10(z_NR))
	return r'$\Delta N_{\mathrm{eff}}='+str(Delta_Neff)+',\,\,z_{\mathrm{NR}}=10^{'+str(log10z_NR)+'}$'

def set_xy_lims(xmin=10, xmax=1000, ymin=1, ymax=1000):
	plt.xlim(xmin, xmax)
	plt.ylim(ymin, ymax)

def add_xy_labels(xlabel=r'$m_\mathrm{lightest}\,\mathrm{[meV]}$', ylabel=r'$n_\nu^\mathrm{loc.}\,\mathrm{[cm}^{-3}\mathrm{]}$', fontsize=20):
	plt.xlabel(xlabel, fontsize=fontsize)
	plt.ylabel(ylabel, fontsize=fontsize)

def set_xy_scales(xscale='linear', yscale='log'):
	plt.xscale(xscale)
	plt.yscale(yscale)

def cosmo_color(case='LCDM'):
	colors_dict = {
        'FD': '#dc267f',
        'BE': '#785ef0',
        'RD': '#648fff',
        'LNwide': '#ffb000',
		'LNsharp': '#fe6100',
        # '??': '#fe6100',
    }
	
	try:
		return colors_dict[case]
	except:
		log('Case not recognised, available cosmo scenarios are:', level='ERROR')
		log('\t(1) Key: FD - FD distribution', level='ERROR')
		log('\t(2) Key: BE - BE distribution', level='ERROR')
		log('\t(3) Key: RD - Out-of-equilibrium relativistic decay product distribution', level='ERROR')
		log('\t(4) Key: LN - Log-normal proxy distribution', level='ERROR')
		return 'k'