import numpy as np
import matplotlib.pyplot as plt
from scipy.special import zeta
import matplotlib as mpl
import scipy.integrate as integrate
from scipy import constants
from classy import Class
# modules for data I/O
import pickle
import os 
T0CMB = 2.7255
nu_factor = (4/11)**(1/3)  # T_nu0 (instantaneous decoupling) / T_CMB0
K_to_eV = constants.physical_constants['Boltzmann constant in eV/K'][0]
hbar = constants.physical_constants['reduced Planck constant in eV s'][0]
c = constants.speed_of_light
eV_to_cm = (hbar * c * 1e2)**(-1)  # eV to cm^-1

#
# Cosmology functions
#

# defining distributions
def f_FD(xi):
	return 1./(np.exp(xi)+1)
def f_BE(xi):
	return 1./(np.exp(xi)-1)
def f_RD(xi):
	return 2.19*pow(xi,-5./2.)*np.exp(-0.74*pow(xi,2.))
def f_LN(xi,sigma):
	return 1./(xi*sigma*np.sqrt(2*np.pi))*np.exp(-pow(np.log(xi),2)/(2*pow(sigma,2)))

# n-th moment of f(xi)
def Qn(f,n,sigma=1):
	if f in [f_FD,f_BE,f_RD]:
		return integrate.quad(lambda xi: xi**(2+n)*f(xi), 0, np.inf)[0]
	elif f == f_LN:
		return integrate.quad(lambda xi: xi**(2+n)*f(xi,sigma), 0, np.inf)[0]
	else: 
		print('[utils.py] (ERROR) Distrib not recognised, assuming FD.')
		return integrate.quad(lambda xi: xi**(2+n)*f_FD(xi), 0, np.inf)[0]


def build_LN_Q_cache(sigma_array, output_dir='../data/distribution_data/LN_Q_cache/'):
	"""Ensure a pickle cache of Q0/Q1 for log-normal sigmas exists and return a dict sigma->(Q0,Q1).

	This cache speeds up repeated evaluations that depend only on the LN shape (not on cosmology).
	Missing sigmas will be computed and the cache updated on-disk.
	"""
	os.makedirs(output_dir, exist_ok=True)
	cache_file = os.path.join(output_dir, 'LN_Q_cache.pkl')
	if os.path.exists(cache_file):
		try:
			with open(cache_file, 'rb') as f:
				q_cache = pickle.load(f)
		except Exception:
			q_cache = {}
	else:
		q_cache = {}

	# compute missing entries
	for sigma in sigma_array:
		# use rounded key to avoid float precision discrepancies
		key = float(np.round(sigma, 10))
		if key in q_cache:
			continue
		Q0_sigma = Qn(f_LN, 0, sigma)
		Q1_sigma = Qn(f_LN, 1, sigma)
		q_cache[key] = (Q0_sigma, Q1_sigma)

	# save updated cache
	with open(cache_file, 'wb') as f:
		pickle.dump(q_cache, f)

	return q_cache

# characteristic momentum from 1st moment and Delta Neff (in units of the photon temp)
def T0chi(Q1,Delta_Neff,g):
	return pow(Delta_Neff/(g/2)/(Q1/(7*np.pi**4/120)),1/4)*nu_factor # in units of T_CMB0 for CLASS

# mass in eV
def m_chi(T0chi,z_NR,Q0,Q1):
	K_to_eV = constants.physical_constants['Boltzmann constant in eV/K'][0]
	return T0chi*T0CMB*K_to_eV*(z_NR+1)*Q1/Q0

# Precomputed moments for canonical distributions
Q0_dict = {
	'FD':3/2*zeta(3),
	'BE':2*zeta(3),
	'RD':Qn(f_RD,0),
}

Q1_dict = {
	'FD':7*np.pi**4/120,
	'BE':6*np.pi**4/90,
	'RD':Qn(f_RD,1),
}

g_dict = {
	'FD':2,
	'BE':1,
	'RD':2,
	'LN':2,
}
	
def LiMR_parameters(Delta_Neff=0.3, z_NR=1e3, sigma_array=None, output_dir='../data/distribution_data/LN_Q_cache/'):
	"""Return T0 and m dictionaries for the canonical distributions and (optionally) for a set of LN sigmas.

	If `sigma_array` is provided, this function will use a cached table of LN Q-moments (Q0,Q1)
	generated by `build_LN_Q_cache` to compute T0 and m for each sigma and include entries named
	`LN_{sigma:.3f}` in the returned dictionaries.
	"""

	T0_dict = {}
	m_dict = {}
	for case in ['FD', 'BE', 'RD']:
		# Compute T0 and m for canonical distributions
		T0_dict[case] = T0chi(Q1_dict[case], Delta_Neff, g_dict[case])
		m_dict[case] = m_chi(T0_dict[case], z_NR, Q0_dict[case], Q1_dict[case])

	# If sigma grid is requested, add entries for each sigma.
	if sigma_array is not None and len(sigma_array) > 0:
		# Ensure LN Q-cache exists for these sigmas
		q_cache = build_LN_Q_cache(sigma_array, output_dir=output_dir)
		for sigma in sigma_array:
			key = f'LN_{sigma:.3f}'
			sigma_key = float(np.round(sigma, 10))
			Q0_sigma, Q1_sigma = q_cache[sigma_key]
			T0_sigma = T0chi(Q1_sigma, Delta_Neff, 2)
			m_sigma = m_chi(T0_sigma, z_NR, Q0_sigma, Q1_sigma)
			T0_dict[key] = T0_sigma
			m_dict[key] = m_sigma

	return T0_dict, m_dict

def_T0_dict, def_m_dict = LiMR_parameters(sigma_array=[0.04, 1.5])
	
def run_CLASS_and_save(case, Delta_Neff=0.3, z_NR=1e3, T0_dict=def_T0_dict, m_dict=def_m_dict, fixed='h', output_dir='../data/distribution_data/'):
	h = 0.67810                       # Dimensionless reduced Hubble parameter (H_0 / (100km/s/Mpc))
	theta_s100 = 1.041783             # Angular size of the sound horizon, exactly 100(ds_dec/da_dec)
	omega_m = 0.1431354439            # Reduced total matter density (Omega*h^2) (Exactly, omega_m = omega_b + omega_cdm + omega_mnu with Mnu=0.06 eV)
	omega_cdm = 0.1201075             # Reduced cold dark matter density in absence of LiMRs (Omega*h^2)
	
    # Initialize CLASS
	cosmo = Class()

    # Use default parameters
	cosmo.set({'output':'tCl,pCl,lCl,mPk',
			   'P_k_max_1/Mpc':10,
			   'l_max_scalars':2500,
			   'lensing': 'yes',
			   'write_background':'yes',            # Write background parameter table
			   'background_verbose': 3,
			   'thermodynamics_verbose': 1,
			   'perturbations_verbose': 1,
			   'input_verbose': 1,
			   'transfer_verbose': 1,
			   'primordial_verbose': 1,
			   'harmonic_verbose': 1,
			   'fourier_verbose': 1,
			   'lensing_verbose': 1,
			   'output_verbose': 1,
			})
	
	print('[utils.py] Computing CLASS with', case, 'parameters.')
    # Modify parameters according to case
	if case == 'LCDM':
		cosmo.set({'N_ncdm':1,
                   'm_ncdm':0.06,
                   'T_ncdm':0.71611,
                   'N_ur':2.0308,
                   'omega_m':omega_m,
                   })
		root = output_dir+case+'_fixed='+fixed
	elif case == 'DR':
		cosmo.set({'N_ncdm':1,
                   'm_ncdm':0.06,
                   'T_ncdm':0.71611,
                   'N_ur':2.0308+Delta_Neff,
                   'omega_m':omega_m,
                   })
		root = output_dir+case+'_DNeff='+str(Delta_Neff)+'_fixed='+fixed
	elif case == 'FD' or case == 'BE' or case == 'RD' or case == 'LN':
		cosmo.set({'N_ncdm':2,
                   'm_ncdm':str(m_dict[case])+', 0.06',
                   'T_ncdm':str(T0_dict[case])+', 0.71611',
                   'omega_m':omega_m,
                   'N_ur':2.0308,
                   })
		root = output_dir+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)+'_fixed='+fixed
	else:
		print('[utils.py] (ERROR) Case not recognised, using LCDM parameters.')
		cosmo.set({'N_ncdm':1,
                   'm_ncdm':0.06,
                   'T_ncdm':0.71611,
                   'N_ur':2.0308,
                   'omega_m':omega_m,
                   })
		root = output_dir+'LCDM_fixed='+fixed
	if fixed == 'theta_s100':
		print('[utils.py] Fixed 100*theta_s requested, H0 will instead vary.')
		cosmo.set({'100*theta_s':theta_s100})
	
	# pip installed class allows writing parameters but not output files oddly, those have to be saved manually
	cosmo.set({
		'write parameters': 'yes',
		'root':root+'_',
	})

	cosmo.compute()

	# save output to file
	filename = root + '_output.pkl'
	bg = cosmo.get_background()
	unlensed_cls = cosmo.raw_cl()
	lensed_cls = cosmo.lensed_cl()
	kvec = np.logspace(-4,1,2500)
	pk = [cosmo.pk(kk, 0.0) for kk in kvec]
	derived = cosmo.get_current_derived_parameters(['rs_rec', 'H0', 'z_reio', 'a_eq', '100*theta_s', 'z_rec'])
	output_data = {
		'background': bg,
		'unlensed_cls': unlensed_cls,
		'lensed_cls': lensed_cls,
		'kvec': kvec,
		'pk': pk,
		'derived': derived,
	}
	with open(filename, 'wb') as f:
		pickle.dump(output_data, f)
	print('[utils.py] CLASS output saved to:', filename)

	cosmo.struct_cleanup()
	cosmo.empty()

	return output_data
	
def fill_cosmos(Delta_Neff=0.3, z_NR=1e3, fixed='h', output_dir='../data/distribution_data/'):
	for case in ['LCDM', 'DR', 'FD']:
		filename = ''
		if case == 'LCDM':
			filename = output_dir+case+'_fixed='+fixed+'_output.pkl'
		elif case == 'DR':
			filename = output_dir+case+'_DNeff='+str(Delta_Neff)+'_fixed='+fixed+'_output.pkl'
		else:
			filename = output_dir+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)+'_fixed='+fixed+'_output.pkl'
		if os.path.exists(filename):
			with open(filename, 'rb') as f:
				output_data = pickle.load(f)
			print('[utils.py] Loaded CLASS output for', case, 'from:', filename)
		else:
			T0_dict, m_dict = fill_LiMR_parameters(Delta_Neff, z_NR, output_dir)
			output_data = run_CLASS_and_save(case, Delta_Neff, z_NR, T0_dict, m_dict, fixed, output_dir)
		globals()[f'cosmo_{case}'] = output_data

#
# Plotting functions
#
def plot_distributions_lin(Delta_Neff=0.3,z_NR=1e3):
	# choose LN sigma grid for plotting continuous band
	sigma_min = 0.04
	sigma_max = 1.5
	n_sigma = 200
	sigma_array = np.linspace(sigma_min, sigma_max, n_sigma)

	# request LiMR parameters including per-sigma entries (this uses the LN Q-cache)
	T0_dict, m_dict = LiMR_parameters(Delta_Neff, z_NR, sigma_array=sigma_array)
	xi_array = np.geomspace(1e-4, 1e5, 40000)
	ymax = 0.
	
	# Now plot LN sigma band 
	c0 = mpl.colors.to_rgb(cosmo_color('LNsharp'))
	c1 = mpl.colors.to_rgb(cosmo_color('LNwide'))
	ln_curves = []
	for i, sigma in enumerate(sigma_array):
		key = f'LN_{sigma:.3f}'
		if key not in m_dict or key not in T0_dict:
			# skip missing entries (shouldn't happen if LiMR_parameters ran correctly)
			continue
		m_sigma = m_dict[key]
		T0_sigma = T0_dict[key]
		curve = m_sigma*(T0_sigma*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict['LN'] / (2 * np.pi**2) * f_LN(xi_array,sigma) * xi_array**3
		ln_curves.append(curve)
		t = float(i) / (len(sigma_array) - 1)
		color = (c0[0] * (1 - t) + c1[0] * t,
				 c0[1] * (1 - t) + c1[1] * t,
				 c0[2] * (1 - t) + c1[2] * t)
		plt.plot(xi_array, curve, c=color, alpha=0.1, lw=2)
		if i%20 == 0:
			plt.plot(xi_array, curve, c=color, alpha=0.6, lw=2)

	# emphasize endpoints
	if len(ln_curves) > 0:
		sharp_curve = ln_curves[0]
		wide_curve = ln_curves[-1]
		plt.plot(xi_array, sharp_curve, c=cosmo_color('LNsharp'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_min}$')
		plt.plot(xi_array, wide_curve, c=cosmo_color('LNwide'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_max}$')
		peak_value = np.max(np.vstack(ln_curves))
		if peak_value > ymax:
			ymax = peak_value

	# Now plot canonical distributions
	for case in ['FD', 'BE', 'RD']:
		d_rhoNR_dlogq = lambda xi, case=case: m_dict[case]*(T0_dict[case]*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict[case] / (2 * np.pi**2) * eval(f'f_{case}(xi)') * xi**3
		plt.plot(
			xi_array,
			d_rhoNR_dlogq(xi_array),
			c=cosmo_color(case),
			lw=2.2,
			label=case)
		peak_value = np.max(d_rhoNR_dlogq(xi_array))
		if peak_value > ymax:
			ymax = peak_value
	plt.legend(fontsize=14)

	ymax = ymax / 0.8
	ymax_rounded = round(ymax, -int(np.floor(np.log10(ymax))))
	
	return ymax_rounded

def plot_distributions_log(Delta_Neff=0.3,z_NR=1e3):
	# choose LN sigma grid for plotting continuous band
	sigma_min = 0.04
	sigma_max = 1.5
	n_sigma = 200
	sigma_array = np.linspace(sigma_min, sigma_max, n_sigma)

	# request LiMR parameters including per-sigma entries (this uses the LN Q-cache)
	T0_dict, m_dict = LiMR_parameters(Delta_Neff, z_NR, sigma_array=sigma_array)
	xi_array = np.geomspace(1e-4, 1e5, 40000)
	ymax = 0.
	
	# Now plot LN sigma band 
	c0 = mpl.colors.to_rgb(cosmo_color('LNsharp'))
	c1 = mpl.colors.to_rgb(cosmo_color('LNwide'))
	ln_curves = []
	for i, sigma in enumerate(sigma_array):
		key = f'LN_{sigma:.3f}'
		if key not in m_dict or key not in T0_dict:
			# skip missing entries (shouldn't happen if LiMR_parameters ran correctly)
			continue
		m_sigma = m_dict[key]
		T0_sigma = T0_dict[key]
		curve = np.log(m_sigma*(T0_sigma*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict['LN'] / (2 * np.pi**2) * f_LN(xi_array,sigma) * xi_array**3)
		ln_curves.append(curve)
		t = float(i) / (len(sigma_array) - 1)
		color = (c0[0] * (1 - t) + c1[0] * t,
				 c0[1] * (1 - t) + c1[1] * t,
				 c0[2] * (1 - t) + c1[2] * t)
		plt.plot(xi_array, curve, c=color, alpha=0.1, lw=2)
		if i%20 == 0:
			plt.plot(xi_array, curve, c=color, alpha=0.6, lw=2)

	# emphasize endpoints
	if len(ln_curves) > 0:
		sharp_curve = ln_curves[0]
		wide_curve = ln_curves[-1]
		plt.plot(xi_array, sharp_curve, c=cosmo_color('LNsharp'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_min}$')
		plt.plot(xi_array, wide_curve, c=cosmo_color('LNwide'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_max}$')
		peak_value = np.max(np.vstack(ln_curves))
		if peak_value > ymax:
			ymax = peak_value

	# Now plot canonical distributions
	for case in ['FD', 'BE', 'RD']:
		d_logrhoNR_dlogq = lambda xi, case=case: np.log(m_dict[case]*(T0_dict[case]*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict[case] / (2 * np.pi**2) * eval(f'f_{case}(xi)') * xi**3)
		plt.plot(
			xi_array,
			d_rhoNR_dlogq(xi_array),
			c=cosmo_color(case),
			lw=2.2,
			label=case)
		peak_value = np.max(d_rhoNR_dlogq(xi_array))
		if peak_value > ymax:
			ymax = peak_value
	plt.legend(fontsize=14)

	ymax = ymax / 0.8
	ymax_rounded = round(ymax, -int(np.floor(np.log10(ymax))))
	
	return ymax_rounded


def add_cosmo_cases():
	xoff, yoff, offset = 0.15, -0.0, 0.03
	plt.text(0.2 - xoff, 0.90 - yoff,r"\boldmath{$\Lambda$}\textbf{CDM}",transform=plt.gca().transAxes,
		fontsize=14,
		color=cosmo_color('LCDM'),
		rotation=0)
	plt.text(0.35, 0.09, r"\boldmath{$\Lambda$}\textbf{CDM}",
		transform=plt.gca().transAxes,
		fontsize=10,
		color=cosmo_color('LCDM'),
		rotation=42)
	plt.text(0.38 - xoff, 0.89 - yoff,r"$\sum m_\nu = 0.12\,\mathrm{eV}$, $N_{\rm eff}^\nu = 3.044$",
		transform=plt.gca().transAxes,
		fontsize=14,
		color='k',
		rotation=0)

	plt.text(0.2 - xoff, 0.82 + offset - yoff,r"\textbf{L}\boldmath{$\nu$}\textbf{-DR}",
		transform=plt.gca().transAxes,
		fontsize=14,
		color=cosmo_color('LEDR'),
		rotation=0)
	plt.text(0.11, 0.09,r"\textbf{L}\boldmath{$\nu$}\textbf{-DR}",
			transform=plt.gca().transAxes,
		fontsize=10,
		color=cosmo_color('LEDR'),
		rotation=62)
	plt.text(0.38 - xoff, 0.81 + offset - yoff,r"$\sum m_\nu = 0.12\,\mathrm{eV}$, $N_{\rm eff}^\nu = 0.5$, $N_{\rm eff}^{\rm DR} = 2.544$",
		transform=plt.gca().transAxes,
		fontsize=14,
		color='k',
		rotation=0)

	plt.text(0.2 - xoff, 0.74 + 2 * offset - yoff, r"\textbf{H}\boldmath{$\nu$}",
		transform=plt.gca().transAxes,
		fontsize=14,
		color=cosmo_color('HE'),
		rotation=0)
	plt.text(0.77, 0.32, r"\textbf{H}\boldmath{$\nu$}",
		transform=plt.gca().transAxes,
		fontsize=12,
		color=cosmo_color('HE'),
		rotation=80)
	plt.text(0.38 - xoff, 0.73 + 2 * offset - yoff,r"$\sum m_\nu = 1.20\,\mathrm{eV}$, $N_{\rm eff}^\nu = 3.044$",
		transform=plt.gca().transAxes,
		fontsize=14,
		color='k',
		rotation=0)

	plt.text(0.2 - xoff, 0.66 + 3 * offset - yoff,r"\textbf{H}\boldmath{$\nu$}\textbf{-DR}",
		transform=plt.gca().transAxes,
		fontsize=14,
		color=cosmo_color('HEDR'),
		rotation=0)
	plt.text(0.61, 0.09,r"\textbf{H}\boldmath{$\nu$}\textbf{-DR}",
		transform=plt.gca().transAxes,
		fontsize=10,
		color=cosmo_color('HEDR'),
		rotation=63)
	plt.text(0.38 - xoff, 0.65 + 3 * offset - yoff,r"$\sum m_\nu = 1.20\,\mathrm{eV}$, $N_{\rm eff}^\nu = 1.5$, $N_{\rm eff}^{\rm DR} = 1.544$",
		transform=plt.gca().transAxes,
		fontsize=14,
		color='k',
		rotation=0)

	plt.text(0.2 - xoff, 0.58 + 4 * offset - yoff,r"\textbf{LT+Mid}",transform=plt.gca().transAxes,
		fontsize=14,
		color=cosmo_color('LTM'),
		rotation=0)
	plt.text(0.455,0.24,r"\textbf{LT+Mid}",transform=plt.gca().transAxes,
		fontsize=10,
		color=cosmo_color('LTM'),
		rotation=83)
	plt.text(0.38 - xoff, 0.57 + 4 * offset - yoff,r"$\sum  m_\nu = 0.12\,\mathrm{eV}$, $N_{\rm eff}^{\nu} = 3.044$",
		transform=plt.gca().transAxes,
		fontsize=14,
		color='k',
		rotation=0)

	plt.text(0.2 - xoff, 0.55 + 2 * offset - yoff,r"$\Omega_{\nu,0} / \Omega_{\mathrm{m},0} = 0.009$, $N_{\rm eff} = 3.044$",
		transform=plt.gca().transAxes,
		fontsize=16,
		color='k',
		rotation=0)
	
def set_xy_lims(xmin=10, xmax=1000, ymin=1, ymax=1000):
	plt.xlim(xmin, xmax)
	plt.ylim(ymin, ymax)

def add_xy_labels(xlabel=r'$m_\mathrm{lightest}\,\mathrm{[meV]}$', ylabel=r'$n_\nu^\mathrm{loc.}\,\mathrm{[cm}^{-3}\mathrm{]}$', fontsize=20):
	plt.xlabel(xlabel, fontsize=fontsize)
	plt.ylabel(ylabel, fontsize=fontsize)

def set_xy_scales(xscale='linear', yscale='log'):
	plt.xscale(xscale)
	plt.yscale(yscale)

HIGHP_LABEL = r'$\mathrm{High-}p_\nu$'
LOWT_LABEL = r'$\mathrm{Low-}T_\nu\mathrm{+DR}$'
LCDM_LABEL = r'$\Lambda\mathrm{CDM}$'

def cosmo_color(case='LCDM'):
	colors_dict = {
        'FD': '#dc267f',
        'BE': '#785ef0',
        'RD': '#648fff',
        'LNwide': '#ffb000',
		'LNsharp': '#fe6100',
        # '??': '#fe6100',
    }
	
	try:
		return colors_dict[case]
	except:
		print('[utils.py] (ERROR) Case not recognised, available cosmo scenarios are:')
		print('[utils.py] \t(1) Key: FD - FD distribution')
		print('[utils.py] \t(2) Key: BE - BE distribution')
		print('[utils.py] \t(3) Key: RD - Out-of-equilibrium relativistic decay product distribution')
		print('[utils.py] \t(4) Key: LN - Log-normal proxy distribution')
		return 'k'