import numpy as np
import matplotlib.pyplot as plt
from scipy.special import zeta
import matplotlib as mpl
import scipy.integrate as integrate
from scipy import constants
from classy import Class
# modules for data I/O
import pickle
import os 
T0CMB = 2.7255 # in Kelvin
nu_factor = (4/11)**(1/3)  # T_nu0 (instantaneous decoupling) / T_CMB0
T0nu = T0CMB*0.71611 # with precise decoupling, in Kelvin
K_to_eV = constants.physical_constants['Boltzmann constant in eV/K'][0]
hbar = constants.physical_constants['reduced Planck constant in eV s'][0]
c = constants.speed_of_light
eV_to_cm = (hbar * c * 1e2)**(-1)  # eV to cm^-1

#
# Cosmology functions
#

# defining distributions
def f_FD(xi):
	return 1./(np.exp(xi)+1)
def f_BE(xi):
	return 1./(np.exp(xi)-1)
def f_RD(xi):
	return 2.19*pow(xi,-5./2.)*np.exp(-0.74*pow(xi,2.))
def f_LN(xi,sigma):
	return 1./(xi*sigma*np.sqrt(2*np.pi))*np.exp(-pow(np.log(xi),2)/(2*pow(sigma,2)))

# n-th moment of f(xi)
def Qn(f,n,sigma=1):
	if f in [f_FD,f_BE,f_RD]:
		return integrate.quad(lambda xi: xi**(2+n)*f(xi), 0, np.inf)[0]
	elif f == f_LN:
		return integrate.quad(lambda xi: xi**(2+n)*f(xi,sigma), 0, np.inf)[0]
	else: 
		print('[utils.py] (ERROR) Distrib not recognised, assuming FD.')
		return integrate.quad(lambda xi: xi**(2+n)*f_FD(xi), 0, np.inf)[0]


def build_LN_Q_cache(sigma_array, output_dir='../data/distribution_data/LN_Q_cache/'):
	"""Ensure a pickle cache of Q0/Q1 for log-normal sigmas exists and return a dict sigma->(Q0,Q1).

	This cache speeds up repeated evaluations that depend only on the LN shape (not on cosmology).
	Missing sigmas will be computed and the cache updated on-disk.
	"""
	os.makedirs(output_dir, exist_ok=True)
	cache_file = os.path.join(output_dir, 'LN_Q_cache.pkl')
	if os.path.exists(cache_file):
		try:
			with open(cache_file, 'rb') as f:
				q_cache = pickle.load(f)
		except Exception:
			q_cache = {}
	else:
		q_cache = {}

	# compute missing entries
	for sigma in sigma_array:
		# use rounded key to avoid float precision discrepancies
		key = float(np.round(sigma, 10))
		if key in q_cache:
			continue
		Q0_sigma = Qn(f_LN, 0, sigma)
		Q1_sigma = Qn(f_LN, 1, sigma)
		q_cache[key] = (Q0_sigma, Q1_sigma)

	# save updated cache
	with open(cache_file, 'wb') as f:
		pickle.dump(q_cache, f)

	return q_cache

# characteristic momentum from 1st moment and Delta Neff (in units of the photon temp)
def T0chi(Q1,Delta_Neff,g):
	return pow(Delta_Neff/(g/2)/(Q1/(7*np.pi**4/120)),1/4)*nu_factor # in units of T_CMB0 for CLASS

# mass in eV
def m_chi(T0chi,z_NR,Q0,Q1):
	return T0chi*T0CMB*K_to_eV*(z_NR+1)*Q1/Q0

# LiMR physical matter density 
def omega_chi(Delta_Neff,z_NR):
	return Delta_Neff*(1+z_NR)*(7*np.pi**4/120)**(-1)*3/2*zeta(3)*T0nu*K_to_eV/93.14 

# Precomputed moments for canonical distributions
Q0_dict = {
	'FD':3/2*zeta(3),
	'BE':2*zeta(3),
	'RD':Qn(f_RD,0),
}

Q1_dict = {
	'FD':7*np.pi**4/120,
	'BE':6*np.pi**4/90,
	'RD':Qn(f_RD,1),
}

g_dict = {
	'FD':2,
	'BE':1,
	'RD':2,
	'LN':2,
}
	
def LiMR_parameters(Delta_Neff=0.3, z_NR=1e3, sigma_array=None, head_dir='../data/'):
	"""Return T0 and m dictionaries for the canonical distributions and (optionally) for a set of LN sigmas.

	If `sigma_array` is provided, this function will use a cached table of LN Q-moments (Q0,Q1)
	generated by `build_LN_Q_cache` to compute T0 and m for each sigma and include entries named
	`LN_{sigma:.3f}` in the returned dictionaries.
	"""

	T0_dict = {}
	m_dict = {}
	for case in ['FD', 'BE', 'RD']:
		# Compute T0 and m for canonical distributions
		T0_dict[case] = T0chi(Q1_dict[case], Delta_Neff, g_dict[case])
		m_dict[case] = m_chi(T0_dict[case], z_NR, Q0_dict[case], Q1_dict[case])

	# If sigma grid is requested, add entries for each sigma.
	if sigma_array != None and len(sigma_array) > 0:
		# Ensure LN Q-cache exists for these sigmas
		output_dir = head_dir+'distribution_data/LN_Q_cache'
		q_cache = build_LN_Q_cache(sigma_array, output_dir=output_dir)
		for sigma in sigma_array:
			key = f'LN_{sigma:.3f}'
			sigma_key = float(np.round(sigma, 10))
			Q0_sigma, Q1_sigma = q_cache[sigma_key]
			T0_sigma = T0chi(Q1_sigma, Delta_Neff, 2)
			m_sigma = m_chi(T0_sigma, z_NR, Q0_sigma, Q1_sigma)
			T0_dict[key] = T0_sigma
			m_dict[key] = m_sigma

	return T0_dict, m_dict

def_T0_dict, def_m_dict = LiMR_parameters(sigma_array=None)
# print(def_T0_dict, def_m_dict)


def ncdm_flags(case,sigma=None):
	ncdm_flags_dict = {
	'FD':'0,0,0',
	'BE':'1,0,0',
	'RD':'3,0,0',
	'LN':'2,0.5,0',#default sigma=0.5
	}
	if sigma != None:
		ncdm_flags_dict['LN'] = '2,'+str(sigma)+',0'
	return ncdm_flags_dict[case]

def ncdm_strategy(case,sigma=None,N_mnu=1):
	if case == 'RD' or (case == 'LN' and sigma != None and not 0.24 <= sigma <= 0.77):
		LiMR_strat = '3' #use adaptive quadrature for RD or LN if sigma is close to extrema as it speeds up sampling here over default
	else:
		LiMR_strat = '0' #default
	# vectorize output as string for N_mnu > 0 massive neutrinos
	return LiMR_strat + ',' + ','.join(['0' for x in range(N_mnu)]) # Potentially non-standard strategy for LiMR, default for massive nus

def ncdm_bins(case,N_mnu=1):
	# this function returns the minimum number of bins required to get suitable sampling accuracy for the RD or LN distribution in our custom scheme, vectorized for 1 LiMR + N_mnu massive nus
	# (Values are ignored for default sampler which uses adaptive scheme to minimize bins for each distribution)
	if case == 'RD':
		N_custom = 30
	else:
		N_custom = 20
	return ','.join([str(N_custom) for x in range(N_mnu+1)]) 

def ncdm_scaler(case,N_mnu=1):
	# this function returns the a-scaling factor for the custom quadrature scheme to ensure sufficient sampling of flat RD/LN distributions, vectorized for 1 LiMR + N_mnu massive nus
	# (Values are ignored for default sampler)
	if case == 'RD':
		a_scaler = 5 # this is simply value that returned expected values for DNeff and rho at late times in tests
	else:
		a_scaler = 1 # this will be overwritten with value from interpolation table for LN distribution
	return ','.join([str(a_scaler) for x in range(N_mnu+1)])

def ncdm_qmax(case,N_mnu=1):
	# this function returns the maximum q to sample for the custom quadrature scheme to ensure sufficient sampling of extended RD/LN distributions, vectorized for 1 LiMR + N_mnu massive nus
	# (Values are ignored for default sampler)
	if case == 'RD':
		qmax = 1000
	else:
		qmax = 15 # this will be overwritten with value from interpolation table for LN distribution, and q_min != 0 chosen as well
	return ','.join([str(qmax) for x in range(N_mnu+1)])

def run_CLASS_and_save(case='LCDM', Delta_Neff=0.3, z_NR=1e3, sigma=None, T0_dict=None, m_dict=None, N_mnu = 1, M_mnu = 0.06, fixed='h', head_dir='../data/'):
	"""Run CLASS for a given case and save outputs.

	This function writes a pickle with CLASS outputs. Files are written under `head_dir+'/fixed={fixed}/N_mnu={str(N_mnu)}_Mmnu={str(M_mnu)}/'`.
	"""
	h = 0.67810                       # Dimensionless reduced Hubble parameter (H_0 / (100km/s/Mpc))
	theta_s100 = 1.041783             # Angular size of the sound horizon, exactly 100(ds_dec/da_dec)
	omega_m = 0.1431354439            # Reduced total matter density (Omega*h^2) (Exactly, omega_m = omega_b + omega_cdm + omega_mnu with Mnu=0.06 eV)
	omega_cdm = 0.1201075             # Reduced cold dark matter density in absence of LiMRs (Omega*h^2)
	if T0_dict == None or m_dict == None:
		T0_dict, m_dict = LiMR_parameters(Delta_Neff,z_NR,np.asarray(sigma),head_dir)
	
	nu_ur_array = [
		3.044,
		2.0308,
		1.0176,
		0.00441
	] # Massless neutrino contribution to Neff for N_mnu = 0,1,2,3 massive nus respectively

    # Initialize CLASS
	cosmo = Class()

    # Use default parameters
	cosmo.set({'output':'tCl,pCl,lCl,mPk',
			   'P_k_max_1/Mpc':10,
			   'l_max_scalars':2500,
			   'lensing': 'yes',
			   'write_background':'yes',            # Write background parameter table
			   'background_verbose': 3,
			   #'thermodynamics_verbose': 1,
			   'perturbations_verbose': 1,
			   'input_verbose': 1,
			   #'transfer_verbose': 1,
			   #'primordial_verbose': 1,
			   #'harmonic_verbose': 1,
			   #'fourier_verbose': 1,
			   #'lensing_verbose': 1,
			   'output_verbose': 1,
			   'N_ur':nu_ur_array[N_mnu],
			   'omega_m':omega_m, 
			   # Fix physical matter density, meaning a_eq will decrease with increasing z_NR from that of the equivalent DNeff DR cosmology down to LCDM
			   # Although this does not isolate effect of radiation driving (see, e.g., 2503.04671), it more closely matches MCMC output and keeps rho_tot fixed since H0 is also fixed
			})

	output_dir = head_dir+'fixed='+fixed+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/'
	# if directory does not exist at this path create it now
	if not os.path.exists(output_dir):
		os.makedirs(output_dir)
		print('[utils.py] Created directory:', output_dir)

	print('[utils.py] Computing CLASS with', case, 'parameters.')
	# Modify parameters if N_mnu > 0 
	if N_mnu>0:
		m_ncdm_str = ','.join([str(M_mnu/N_mnu) for x in range(N_mnu)]) # Baseline for LCDM and DR cosmologies, to be appended for LiMR cosmologies
		T_ncdm_str = ','.join(['0.71611' for x in range(N_mnu)])  # Standard neutrino temperature today in units of T_CMB0
		cosmo.set({
			'N_ncdm':N_mnu,
			'm_ncdm':m_ncdm_str,
			'T_ncdm':T_ncdm_str,
		})
	
	# Now go case by case for non-LCDM cosmologies
	if case == 'DR':
		cosmo.set({
			'N_ur':nu_ur_array[N_mnu]+Delta_Neff,
		})
		root = output_dir+case+'_DNeff='+str(Delta_Neff)
	elif case in ['FD', 'BE', 'RD', 'LN']:
		m_ncdm_str = str(m_dict[case])+m_ncdm_str # Append LiMR mass to baseline neutrino masses if any
		T_ncdm_str = str(T0_dict[case])+','+T_ncdm_str # Append LiMR characteristic momentum to baseline neutrino temperatures if any	
		cosmo.set({
			'N_ncdm':N_mnu+1,
			'm_ncdm':m_ncdm_str,
			'T_ncdm':T_ncdm_str,
			'deg_ncdm':float(g_dict[case])/2,
			'ncdm_psd_parameters':ncdm_flags(case,sigma),
			'ncdm_quadrature_strategy':ncdm_strategy(case,sigma,N_mnu),
			'ncdm_N_momentum_bins':ncdm_bins(N_mnu),
			'ncdm_a':ncdm_scaler(N_mnu),
			'ncdm_maximum_q':ncdm_qmax(N_mnu),
		})	
		root = output_dir+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)
		if case == 'LN':
			root = root + '_sigma=' + str(sigma)
	else:
		root = output_dir+case
	if fixed == 'theta_s100':
		print('[utils.py] Fixed 100*theta_s requested, H0 will instead vary.')
		cosmo.set({'100*theta_s':theta_s100})
	
	# pip installed class allows writing parameters but not output files oddly, those have to be saved manually
	cosmo.set({
		'write parameters': 'yes',
		'root':root+'_',
	})

	cosmo.compute()

	# save output to file
	filename = root + '_output.pkl'
	bg = cosmo.get_background()
	print(bg)
	unlensed_cls = cosmo.raw_cl()
	lensed_cls = cosmo.lensed_cl()
	kvec = np.logspace(-4,1,2500)
	pk = [cosmo.pk(kk, 0.0) for kk in kvec]
	derived = cosmo.get_current_derived_parameters(['rs_rec', 'H0', 'z_reio', 'a_eq', '100*theta_s', 'z_rec'])
	output_data = {
		'background': bg,
		'unlensed_cls': unlensed_cls,
		'lensed_cls': lensed_cls,
		'kvec': kvec,
		'pk': pk,
		'derived': derived,
	}
	with open(filename, 'wb') as f:
		pickle.dump(output_data, f)
	print('[utils.py] CLASS output saved to:', filename)

	cosmo.struct_cleanup()
	cosmo.empty()

	return output_data

def fill_cosmos(cases=['LCDM', 'DR', 'FD'], Delta_Neff=0.3, z_NR=1e3, sigma_array=None, T0_dict=None, m_dict=None, N_mnu = 1, M_mnu = 0.06, fixed='h', head_dir='../data/'):
	""" Pickle output from CLASS for a set of cosmological cases.
	Then create global variables for each case with the output data.
	"""
	output_dir = head_dir+'fixed='+fixed+'/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/'
	for case in cases:
		root = output_dir+case
		if case == 'DR':
			root = output_dir+case+'_DNeff='+str(Delta_Neff)
		elif case in ['FD', 'BE', 'RD']:
			root = output_dir+case+'_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NR)
		filename = root + '_output.pkl'
		if os.path.exists(filename):
			with open(filename, 'rb') as f:
				output_data = pickle.load(f)
			print('[utils.py] Loaded CLASS output for', case, 'from:', filename)
		else:
			output_data = run_CLASS_and_save(case, Delta_Neff, z_NR, sigma_array, T0_dict, m_dict, N_mnu, M_mnu, fixed, head_dir)
		globals()[f'cosmo_{root}'] = output_data
			
#
# Plotting functions
#
def plot_distributions_lin(Delta_Neff=0.3,z_NR=1e3):
	# choose LN sigma grid for plotting continuous band
	sigma_min = 0.04
	sigma_max = 1.5
	n_sigma = 200
	sigma_array = np.linspace(sigma_min, sigma_max, n_sigma)

	# request LiMR parameters including per-sigma entries (this uses the LN Q-cache)
	T0_dict, m_dict = LiMR_parameters(Delta_Neff, z_NR, sigma_array=sigma_array)
	xi_array = np.geomspace(1e-4, 1e5, 40000)
	ymax = 0.
	
	# Now plot LN sigma band 
	c0 = mpl.colors.to_rgb(cosmo_color('LNsharp'))
	c1 = mpl.colors.to_rgb(cosmo_color('LNwide'))
	ln_curves = []
	for i, sigma in enumerate(sigma_array):
		key = f'LN_{sigma:.3f}'
		if key not in m_dict or key not in T0_dict:
			# skip missing entries (shouldn't happen if LiMR_parameters ran correctly)
			continue
		m_sigma = m_dict[key]
		T0_sigma = T0_dict[key]
		curve = m_sigma*(T0_sigma*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict['LN'] / (2 * np.pi**2) * f_LN(xi_array,sigma) * xi_array**3
		ln_curves.append(curve)
		t = float(i) / (len(sigma_array) - 1)
		color = (c0[0] * (1 - t) + c1[0] * t,
				 c0[1] * (1 - t) + c1[1] * t,
				 c0[2] * (1 - t) + c1[2] * t)
		plt.plot(xi_array, curve, c=color, alpha=0.1, lw=2)
		if i%20 == 0:
			plt.plot(xi_array, curve, c=color, alpha=0.6, lw=2)

	# emphasize endpoints
	if len(ln_curves) > 0:
		sharp_curve = ln_curves[0]
		wide_curve = ln_curves[-1]
		plt.plot(xi_array, sharp_curve, c=cosmo_color('LNsharp'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_min}$')
		plt.plot(xi_array, wide_curve, c=cosmo_color('LNwide'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_max}$')
		peak_value = np.max(np.vstack(ln_curves))
		if peak_value > ymax:
			ymax = peak_value

	# Now plot canonical distributions
	for case in ['FD', 'BE', 'RD']:
		d_rhoNR_dlogq = lambda xi, case=case: m_dict[case]*(T0_dict[case]*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict[case] / (2 * np.pi**2) * eval(f'f_{case}(xi)') * xi**3
		plt.plot(
			xi_array,
			d_rhoNR_dlogq(xi_array),
			c=cosmo_color(case),
			lw=2.2,
			label=case)
		peak_value = np.max(d_rhoNR_dlogq(xi_array))
		if peak_value > ymax:
			ymax = peak_value
	plt.legend(fontsize=14)

	ymax = ymax / 0.8
	ymax_rounded = round(ymax, -int(np.floor(np.log10(ymax))))
	
	return ymax_rounded

def plot_cosmo_densities(Delta_Neffs=[0.3], z_NRs =[1e3], N_mnu = 1, M_mnu = 0.06, head_dir='../data/'):
	"""
	This function plots the bg energy density evolution for LCDM (with N_mnu massive neutrinos) and for possibly multiple FD LiMR cosmologies.
	It assumes H0 is fixed to 67.81 km/s/Mpc
	"""
	# fill out arrays for background values for plotting, using fill_cosmos
	for i, Delta_Neff in enumerate(Delta_Neffs):
		fill_cosmos(cases=['LCDM','FD'], Delta_Neff=Delta_Neff, z_NR=z_NRs[i], N_mnu=N_mnu, M_mnu=M_mnu, head_dir=head_dir)

	root = head_dir+'fixed=h/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/LCDM'
	z_array = globals()[f'cosmo_{root}']['background']['z']
	a_array = 1/(1+z_array)
	rho_g = globals()[f'cosmo_{root}']['background']['(.)rho_g']
	rho_cdm_LCDM = globals()[f'cosmo_{root}']['background']['(.)rho_cdm']
	rho_nu = globals()[f'cosmo_{root}']['background']['(.)rho_ncdm[0]']+globals()[f'cosmo_{root}']['background']['(.)rho_ur']
	rho_lambda = globals()[f'cosmo_{root}']['background']['(.)rho_lambda']
	rho_crit = globals()[f'cosmo_{root}']['background']['(.)rho_crit']

	for rhos in [rho_g, rho_cdm_LCDM, rho_nu, rho_lambda]:
		Omega_i = rhos/rho_crit
		plt.loglog(
			a_array,
			Omega_i,
			c='k',
			lw=1.0,
			zorder=1,
			# label=rhos
			)
		
	for i, Delta_Neff in enumerate(Delta_Neffs):
		root = head_dir+'fixed=h/N_mnu='+str(N_mnu)+'_Mmnu='+str(M_mnu)+'/FD_DNeff='+str(Delta_Neff)+'_zNR='+str(z_NRs[i])
		rho_LiMR = globals()[f'cosmo_{root}']['background']['(.)rho_ncdm[0]]']
		rho_cdm_LiMR = globals()[f'cosmo_{root}']['background']['(.)rho_cdm']
		for rhos in [rho_LiMR, rho_cdm_LiMR]:
			Omega_i = rhos/rho_crit
			plt.loglog(
				a_array,
				Omega_i,
				c=cosmo_color('FD'),
				lw=2.0,
				# ls='--',
				# zorder=0,
				# label=rhos
				)
	# plt.legend(fontsize=14) 

plot_cosmo_densities()


# def plot_distributions_log(Delta_Neff=0.3,z_NR=1e3):
# 	# choose LN sigma grid for plotting continuous band
# 	sigma_min = 0.04
# 	sigma_max = 1.5
# 	n_sigma = 200
# 	sigma_array = np.linspace(sigma_min, sigma_max, n_sigma)

# 	# request LiMR parameters including per-sigma entries (this uses the LN Q-cache)
# 	T0_dict, m_dict = LiMR_parameters(Delta_Neff, z_NR, sigma_array=sigma_array)
# 	xi_array = np.geomspace(1e-4, 1e5, 40000)
# 	ymax = 0.
	
# 	# Now plot LN sigma band 
# 	c0 = mpl.colors.to_rgb(cosmo_color('LNsharp'))
# 	c1 = mpl.colors.to_rgb(cosmo_color('LNwide'))
# 	ln_curves = []
# 	for i, sigma in enumerate(sigma_array):
# 		key = f'LN_{sigma:.3f}'
# 		if key not in m_dict or key not in T0_dict:
# 			# skip missing entries (shouldn't happen if LiMR_parameters ran correctly)
# 			continue
# 		m_sigma = m_dict[key]
# 		T0_sigma = T0_dict[key]
# 		curve = np.log(m_sigma*(T0_sigma*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict['LN'] / (2 * np.pi**2) * f_LN(xi_array,sigma) * xi_array**3)
# 		ln_curves.append(curve)
# 		t = float(i) / (len(sigma_array) - 1)
# 		color = (c0[0] * (1 - t) + c1[0] * t,
# 				 c0[1] * (1 - t) + c1[1] * t,
# 				 c0[2] * (1 - t) + c1[2] * t)
# 		plt.plot(xi_array, curve, c=color, alpha=0.1, lw=2)
# 		if i%20 == 0:
# 			plt.plot(xi_array, curve, c=color, alpha=0.6, lw=2)

# 	# emphasize endpoints
# 	if len(ln_curves) > 0:
# 		sharp_curve = ln_curves[0]
# 		wide_curve = ln_curves[-1]
# 		plt.plot(xi_array, sharp_curve, c=cosmo_color('LNsharp'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_min}$')
# 		plt.plot(xi_array, wide_curve, c=cosmo_color('LNwide'), lw=2.6, alpha=0.9, label=f'LN $\\sigma={sigma_max}$')
# 		peak_value = np.max(np.vstack(ln_curves))
# 		if peak_value > ymax:
# 			ymax = peak_value

# 	# Now plot canonical distributions
# 	for case in ['FD', 'BE', 'RD']:
# 		d_logrhoNR_dlogq = lambda xi, case=case: np.log(m_dict[case]*(T0_dict[case]*T0CMB*K_to_eV)**3 * eV_to_cm**3 * g_dict[case] / (2 * np.pi**2) * eval(f'f_{case}(xi)') * xi**3)
# 		plt.plot(
# 			xi_array,
# 			d_logrhoNR_dlogq(xi_array),
# 			c=cosmo_color(case),
# 			lw=2.2,
# 			label=case)
# 		peak_value = np.max(d_logrhoNR_dlogq(xi_array))
# 		if peak_value > ymax:
# 			ymax = peak_value
# 	plt.legend(fontsize=14)

# 	ymax = ymax / 0.8
# 	ymax_rounded = round(ymax, -int(np.floor(np.log10(ymax))))
	
# 	return ymax_rounded

# Plotting visual settings
def set_xy_lims(xmin=10, xmax=1000, ymin=1, ymax=1000):
	plt.xlim(xmin, xmax)
	plt.ylim(ymin, ymax)

def add_xy_labels(xlabel=r'$m_\mathrm{lightest}\,\mathrm{[meV]}$', ylabel=r'$n_\nu^\mathrm{loc.}\,\mathrm{[cm}^{-3}\mathrm{]}$', fontsize=20):
	plt.xlabel(xlabel, fontsize=fontsize)
	plt.ylabel(ylabel, fontsize=fontsize)

def set_xy_scales(xscale='linear', yscale='log'):
	plt.xscale(xscale)
	plt.yscale(yscale)

def cosmo_color(case='LCDM'):
	colors_dict = {
        'FD': '#dc267f',
        'BE': '#785ef0',
        'RD': '#648fff',
        'LNwide': '#ffb000',
		'LNsharp': '#fe6100',
        # '??': '#fe6100',
    }
	
	try:
		return colors_dict[case]
	except:
		print('[utils.py] (ERROR) Case not recognised, available cosmo scenarios are:')
		print('[utils.py] \t(1) Key: FD - FD distribution')
		print('[utils.py] \t(2) Key: BE - BE distribution')
		print('[utils.py] \t(3) Key: RD - Out-of-equilibrium relativistic decay product distribution')
		print('[utils.py] \t(4) Key: LN - Log-normal proxy distribution')
		return 'k'